CREATE SCHEMA IF NOT EXISTS public;
SET SCHEMA public;

CREATE TABLE IF NOT EXISTS resources (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    deleted TIMESTAMP
);

CREATE TABLE IF NOT EXISTS resource_data (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    resource_id INTEGER NOT NULL,
    resource_key TEXT NOT NULL,
    resource_value TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    deleted TIMESTAMP,
    UNIQUE (resource_id, resource_key, resource_value)
);